import { Arrow, WingX, Wordmark, MotionGraphic } from "@/components/brand";
import { ProductCard } from "@/components/product-card";
import { process, products } from "@/data/site";

export default function Home() {
  return <main id="conteudo">
    <section id="inicio" className="hero" aria-labelledby="hero-title"><div className="shell hero-inner"><div className="hero-label eyebrow"><span className="signal" /> INDEPENDENT THINKING. CONNECTED BUILDING.</div><div className="hero-content"><div className="hero-copy"><h1 id="hero-title">Ideias em<br />movimento.<br /><span>Produtos</span><br /><span>no mundo.</span></h1><p>Somos a ECAPX. Um Product Studio que transforma problemas reais em produtos digitais que fazem diferença.</p><a className="button button-orange" href="#produtos">Explore nossos produtos <Arrow diagonal /></a></div><MotionGraphic /></div><div className="hero-bottom"><span>ESTRATÉGIA + DESIGN + TECNOLOGIA</span><span className="hero-ecosystem">Um studio. Muitas possibilidades. <span>↘</span></span><a href="#produtos" aria-label="Rolar para os produtos"><span>SCROLL PARA EXPLORAR</span><Arrow className="rotate-90" /></a></div></div></section>
    <section id="produtos" className="products-section section-light" aria-labelledby="products-title"><div className="shell"><div className="section-kicker eyebrow"><span>01 — O QUE COLOCAMOS NO MUNDO</span><span>PORTFÓLIO / 02</span></div><div className="section-heading"><h2 id="products-title">Menos promessa.<br /><span className="muted-heading">Mais produto.</span></h2><p>É no mundo real que uma ideia mostra seu valor. Conheça os primeiros produtos da ECAPX.</p></div><div className="products-grid">{products.map((product) => <ProductCard key={product.id} product={product} />)}</div></div></section>
    <section id="studio" className="studio-section" aria-labelledby="studio-title"><div className="shell"><div className="section-kicker eyebrow"><span>02 — NOSSA NATUREZA</span><span>ECAPX / PRODUCT STUDIO</span></div><div className="studio-layout"><div><span className="small-cross"><WingX /></span><p className="studio-side">Curiosidade para questionar.<br />Intenção para construir.</p></div><div><h2 id="studio-title">A gente vê um problema.<br /><span>E começa a enxergar<br />possibilidades.</span></h2><div className="studio-copy"><p>Existimos para aproximar o que é possível do que é necessário. Unimos visão de produto, design e engenharia para dar forma a soluções que merecem existir.</p><p>De uma operação que precisa fluir a uma ideia que pode se tornar um negócio. Criamos software, automações e soluções com IA com o mesmo ponto de partida: gente e problemas reais.</p></div><div className="capabilities" aria-label="Nossas frentes de atuação"><span>Produtos digitais</span><span>Software</span><span>Automações</span><span>Inteligência artificial</span></div></div></div></div></section>
    <section id="processo" className="process-section section-light" aria-labelledby="process-title"><div className="shell process-layout"><div className="process-intro"><p className="eyebrow">03 — DA PERGUNTA AO PRODUTO</p><h2 id="process-title">Pensar fundo.<br />Criar junto.<br /><span className="muted-heading">Ir além.</span></h2><p>Um processo que conecta descoberta e execução. Com espaço para experimentar e compromisso para fazer acontecer.</p></div><div className="process-steps">{process.map((step, index) => <details key={step.tag} className="process-step" name="process" open={index === 0}><summary><span className="eyebrow">{step.tag}</span><span className="step-title">{step.title}</span><span className="step-toggle" aria-hidden="true" /></summary><p>{step.text}</p></details>)}</div></div></section>
    <section id="ecossistema" className="ecosystem-section" aria-labelledby="ecosystem-title"><div className="shell"><div className="section-kicker eyebrow"><span>04 — CONEXÕES QUE MULTIPLICAM</span><span>PARTE DE ALGO MAIOR</span></div><div className="ecosystem-layout"><div><h2 id="ecosystem-title">Um X em comum.<br />Infinitas direções.</h2><p>A ECAPX faz parte do ecossistema XPACE. Diferentes iniciativas, conectadas pela vontade de transformar ideias em novas possibilidades.</p><a className="text-link" href="#produtos">Conheça os produtos dessa conexão <Arrow diagonal /></a></div><div className="ecosystem-lockup" aria-label="ECAPX faz parte do ecossistema XPACE"><Wordmark dark /><span className="connection-line"><span>+</span></span><span>xpace</span></div></div></div></section>
  </main>;
}
