import { Arrow, WingX, Wordmark, MotionGraphic } from "@/components/brand";
import { ProductCard } from "@/components/product-card";
import { process, projects, institutional } from "@/data/site";

export default function Home() {
  return <main id="conteudo">
    <section id="inicio" className="hero" aria-labelledby="hero-title"><div className="shell hero-inner"><div className="hero-label eyebrow"><span className="signal" /> INDEPENDENT THINKING. CONNECTED BUILDING.</div><div className="hero-content"><div className="hero-copy"><h1 id="hero-title">Ideias em<br />movimento.<br /><span>Produtos</span><br /><span>no mundo.</span></h1><p>Somos a ECAPX. Um Product Studio que transforma problemas reais em produtos digitais que fazem diferença.</p><a className="button button-orange" href="#projetos">Explore nossos projetos <Arrow diagonal /></a></div><MotionGraphic /></div><div className="hero-bottom"><span>ESTRATÉGIA + DESIGN + TECNOLOGIA</span><span className="hero-ecosystem">Um studio. Muitas possibilidades. <span className="hero-ecosystem-arrow" aria-hidden="true"><Arrow diagonal className="rotate-90" /></span></span><a href="#projetos" aria-label="Rolar para os projetos"><span>SCROLL PARA EXPLORAR</span><Arrow className="rotate-90" /></a></div></div></section>
    <section id="projetos" className="projects-section section-light" aria-labelledby="projects-title"><div className="shell"><div className="section-kicker eyebrow"><span>01 — O QUE COLOCAMOS NO MUNDO</span><span>PORTFÓLIO / 03</span></div><div className="section-heading"><h2 id="projects-title">Menos promessa.<br /><span className="muted-heading">Mais projetos.</span></h2><p>É no mundo real que uma ideia mostra seu valor. Conheça alguns dos projetos e produtos da ECAPX.</p></div><div className="projects-grid">{projects.map((project) => <ProductCard key={project.id} product={project} />)}</div></div></section>
    <section id="studio" className="studio-section" aria-labelledby="studio-title"><div className="shell"><div className="section-kicker eyebrow"><span>02 — NOSSA NATUREZA</span><span>ECAPX / PRODUCT STUDIO</span></div><div className="studio-layout"><div><span className="small-cross"><WingX /></span><p className="studio-side">Curiosidade para questionar.<br />Intenção para construir.</p></div><div><h2 id="studio-title">A gente vê um problema.<br /><span>E começa a enxergar<br />possibilidades.</span></h2><div className="studio-copy"><p>Existimos para aproximar o que é possível do que é necessário. Unimos visão de produto, design e engenharia para dar forma a soluções que merecem existir.</p><p>De uma operação que precisa fluir a uma ideia que pode se tornar um negócio. Criamos software, automações e soluções com IA com o mesmo ponto de partida: gente e problemas reais.</p></div><div className="capabilities" aria-label="Nossas frentes de atuação"><span>Produtos digitais</span><span>Software</span><span>Automações</span><span>Inteligência artificial</span></div></div></div></div></section>
    <section id="processo" className="process-section section-light" aria-labelledby="process-title"><div className="shell process-layout"><div className="process-intro"><p className="eyebrow">03 — DA PERGUNTA AO PRODUTO</p><h2 id="process-title">Pensar fundo.<br />Criar junto.<br /><span className="muted-heading">Ir além.</span></h2><p>Um processo que conecta descoberta e execução. Com espaço para experimentar e compromisso para fazer acontecer.</p></div><div className="process-steps">{process.map((step, index) => <details key={step.tag} className="process-step" name="process" open={index === 0}><summary><span className="eyebrow">{step.tag}</span><span className="step-title">{step.title}</span><span className="step-toggle" aria-hidden="true" /></summary><p>{step.text}</p></details>)}</div></div></section>
    <section id="ecossistema" className="ecosystem-section" aria-labelledby="ecosystem-title"><div className="shell"><div className="section-kicker eyebrow"><span>04 — CONEXÕES QUE MULTIPLICAM</span><span>PARTE DE ALGO MAIOR</span></div><div className="ecosystem-layout"><div><h2 id="ecosystem-title">Um X em comum.<br />Infinitas direções.</h2><p>A ECAPX faz parte do ecossistema XPACE. Diferentes iniciativas, conectadas pela vontade de transformar ideias em novas possibilidades.</p><a className="text-link" href="#projetos">Conheça os projetos dessa conexão <Arrow diagonal /></a></div><div className="ecosystem-lockup" aria-label="ECAPX faz parte do ecossistema XPACE"><Wordmark dark /><span className="connection-line"><span>+</span></span><span>xpace</span></div></div></div></section>
    <section id="contato" className="contact-section" aria-labelledby="contact-title"><div className="shell"><div className="section-kicker eyebrow"><span>05 — VAMOS CONVERSAR</span><span>CANAL DIRETO</span></div><div className="contact-layout"><div className="contact-intro"><h2 id="contact-title">Tem um problema real?<br /><span>Vamos construir juntos.</span></h2><p>Seja para tirar uma ideia do papel, estruturar um produto digital ou aplicar tecnologia e automação no seu negócio: o primeiro passo é uma conversa direta.</p><a className="button button-orange" href={institutional.whatsapp.url} target="_blank" rel="noopener noreferrer" aria-label="Conversar no WhatsApp com a ECAPX (abre em nova aba)">Conversar no WhatsApp <Arrow diagonal /></a></div><div className="contact-channels" aria-label="Canais oficiais de contato"><a href={institutional.whatsapp.url} target="_blank" rel="noopener noreferrer" className="contact-card" aria-label={`Conversar via WhatsApp no ${institutional.whatsapp.display} (abre em nova aba)`}><div className="contact-card-top"><span className="eyebrow">CANAL DIRETO / 01</span><span className="contact-card-tag">WHATSAPP</span></div><h3 className="contact-card-title">{institutional.whatsapp.display}</h3><p className="contact-card-desc">Atendimento direto para novos projetos, demandas técnicas e parcerias.</p><div className="contact-card-link"><span>Iniciar conversa</span><Arrow diagonal /></div></a><a href={institutional.instagram.url} target="_blank" rel="noopener noreferrer" className="contact-card" aria-label={`Acompanhar a ECAPX no Instagram ${institutional.instagram.handle} (abre em nova aba)`}><div className="contact-card-top"><span className="eyebrow">PRESENÇA DIGITAL / 02</span><span className="contact-card-tag">INSTAGRAM</span></div><h3 className="contact-card-title">{institutional.instagram.handle}</h3><p className="contact-card-desc">Acompanhe bastidores, lançamentos e reflexões sobre tecnologia e produto.</p><div className="contact-card-link"><span>Seguir no Instagram</span><Arrow diagonal /></div></a></div></div></div></section>
  </main>;
}
