import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs';
import assert from 'node:assert/strict';
(async()=>{
 fs.mkdirSync('verification',{recursive:true});
 const url = process.env.ECAPX_URL || 'http://localhost:3000';
 const browser = await chromium.launch({channel:'chrome', headless:true});
 const context = await browser.newContext();
 const page = await context.newPage();
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 const results=[];
 for(const width of [320,390,768,1024,1440]) {
  await page.setViewportSize({width,height:900});
  await page.goto(url,{waitUntil:'networkidle'});
  const layout=await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth}));
  assert.ok(layout.width<=width, `Horizontal overflow at ${width}: ${layout.width}`);
  const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze();
  results.push({width,layout,violations:audit.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}))});
 }
 await page.setViewportSize({width:390,height:844});
 await page.goto(url,{waitUntil:'networkidle'});
 const menu=page.locator('.mobile-menu');
 await menu.locator('summary').click(); assert.equal(await menu.getAttribute('open'),'');
 await page.keyboard.press('Escape'); assert.equal(await menu.getAttribute('open'),null);
 await menu.locator('summary').click(); await menu.getByRole('link',{name:/Produtos|Projetos/}).first().click();
 await page.waitForURL('**#projetos');
 assert.equal(await menu.getAttribute('open'),null); assert.equal(new URL(page.url()).hash,'#projetos');
 const steps=page.locator('.process-step');
 await steps.nth(1).locator('summary').focus();await page.keyboard.press('Enter');
 assert.equal(await steps.nth(1).getAttribute('open'),''); assert.equal(await steps.nth(0).getAttribute('open'),null);
 await page.emulateMedia({reducedMotion:'reduce'});
 assert.equal(await page.locator('.cross-stack').evaluate(e=>getComputedStyle(e).animationName),'none');
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(url,{waitUntil:'networkidle'});
 await page.screenshot({path:'verification/ecapx-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'verification/ecapx-mobile.png',fullPage:true});
 const typography=await page.evaluate(()=>({title:{font:getComputedStyle(document.querySelector('h1')).fontFamily,transform:getComputedStyle(document.querySelector('h1')).textTransform},detail:{font:getComputedStyle(document.querySelector('.eyebrow')).fontFamily,transform:getComputedStyle(document.querySelector('.eyebrow')).textTransform},body:getComputedStyle(document.querySelector('.hero-copy p')).fontFamily,fonts:[...document.fonts].map(f=>({family:f.family,status:f.status})),images:[...document.images].every(i=>i.complete&&i.naturalWidth>0)}));
 assert.ok(typography.title.font.toLowerCase().includes('chillax'));assert.equal(typography.title.transform,'uppercase');assert.ok(typography.detail.font.toLowerCase().includes('ptmono'));assert.equal(typography.detail.transform,'uppercase');assert.ok(typography.body.toLowerCase().includes('poppins'));assert.ok(typography.images);
 const productLinks=await page.locator('.product-image-link').evaluateAll(es=>es.map(e=>({href:e.href,rel:e.rel,target:e.target})));
 assert.ok(productLinks.some(e=>e.href.includes('xtage.app')));
 assert.ok(productLinks.some(e=>e.href.includes('xpacecompany.com')));
 assert.ok(productLinks.some(e=>e.href.includes('smile-burger')||e.href.includes('osmileburguer')));
 const whatsappLinks=await page.locator('a[href*="wa.me"]').evaluateAll(es=>es.map(e=>({href:e.href,rel:e.rel,target:e.target,text:e.textContent})));
 assert.ok(whatsappLinks.length>=3, `Expected at least 3 WhatsApp links, found ${whatsappLinks.length}`);
 assert.ok(whatsappLinks.every(e=>e.href.startsWith('https://wa.me/554789173116?text=')&&e.target==='_blank'&&e.rel.includes('noopener')));
 const expectedMsg=encodeURIComponent('Olá! Vim pelo site da ECAPX e gostaria de conversar sobre um projeto.');
 assert.ok(whatsappLinks.every(e=>e.href.includes(expectedMsg)), 'WhatsApp message not properly encoded');
 const instagramLinks=await page.locator('a[href*="instagram.com"]').evaluateAll(es=>es.map(e=>({href:e.href,rel:e.rel,target:e.target,text:e.textContent})));
 assert.ok(instagramLinks.length>=2, `Expected at least 2 Instagram links, found ${instagramLinks.length}`);
 assert.ok(instagramLinks.every(e=>e.href==='https://instagram.com/ecapxtech'&&e.target==='_blank'&&e.rel.includes('noopener')));
 assert.ok(instagramLinks.some(e=>e.text.includes('@ecapxtech')), 'Instagram handle @ecapxtech should be displayed');
 await page.setViewportSize({width:1280,height:900});
 await page.evaluate(()=>document.documentElement.style.fontSize='200%');
 const zoom=await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth}));
 assert.ok(zoom.width<=zoom.viewport);
 fs.writeFileSync('verification/ecapx-audit.json',JSON.stringify({results,errors,typography,checks:['menu open/escape/anchor close','keyboard accordion','reduced motion','external product links','200% root font size'],zoom},null,2));
 console.log(JSON.stringify({results,errors,typography,zoom},null,2));
 await browser.close();
 if(errors.length||results.some(r=>r.violations.length))process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
